remote_theme:   "owasp/www--site-theme@main"
plugins:
 - jekyll-include-cache-0.2.0
 - jekyll-redirect-from
  
project:
    name:       "OWASP Top Ten Project"

# The all languages used
languages:      ["en", "de"]

# If not config, the first item of languages will be used as the default.
default_lang:   'en'

languageNames:
  de: Deutsch
  en: English